[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino

; Strip out size optimization AND software float defaults
build_unflags = 
    -Os
    -mfloat-abi=soft

; Force speed optimization AND hardware FPU usage
build_flags = 
    -O2
    -mfloat-abi=softfp
    -mfpu=fpv4-sp-d16
    -Wno-vla
    -Wno-deprecated-declarations

; Warnings scoped to OUR code only
; We re-enable -Wvla here so it warns us if we use them in src
build_src_flags =
    -Wall
    -Wextra
    -Wdouble-promotion
    -Wvla

monitor_speed = 115200

; Pin exact versions for stability and drop ArduinoBLE for now
lib_deps =
    arduino-libraries/Arduino_BMI270_BMM150 @ 1.2.3
    arduino-libraries/Arduino_APDS9960 @ 1.0.4
;   arduino-libraries/ArduinoBLE @ 2.1.0     ; Phase 4